<a href="https://colab.research.google.com/github/Dietrich061991/Aprenda-Como-Selecionar-Features-para-seu-Modelo-de-Machine-Learning/blob/master/Aprenda_Como_Selecionar_Features_para_seu_Modelo_de_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Limpeza de dados e Selecionar Features para seu Modelo de Machine Learning**

# Tratamento e Limpeza dos dados

![alt text](https://media.giphy.com/media/xT39Dj840Y1DEOp1e0/giphy.gif)

In [0]:
import pandas as pd
import numpy as np
from google.colab import drive

In [11]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [12]:
df =  pd.read_excel ('/content/drive/My Drive/Python-Machine-Learning/PIMPF.xlsx')
df.head(5)

PIMPF - Produção física industrial por grupos e classes industriais selecionados  ...                                         Unnamed: 7
0                                Brasil - abril 2020                                ...                                                NaN
1          Grupos e classes industriais selecionados                                ...                                                NaN
2                                                NaN                                ...  Variação percentual acumulada nos últimos 12 m...
3       10.1 Abate e fabricação de produtos de carne                                ...                                                3.2
4                10.11 Abate de reses, exceto suínos                                ...                                               -1.5

[5 rows x 8 columns]

**Vamos renomear as colunas**

In [0]:
df= df.rename(columns={"Unnamed: 1": "A", "Unnamed: 2": "B","Unnamed: 3": "C","Unnamed: 4": "D","Unnamed: 5": "E","Unnamed: 6": "F","Unnamed: 7": "G"})

In [14]:
df.columns

Index(['PIMPF - Produção física industrial por grupos e classes industriais selecionados',
       'A', 'B', 'C', 'D', 'E', 'F', 'G'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 8 columns):
 #   Column                                                                            Non-Null Count  Dtype 
---  ------                                                                            --------------  ----- 
 0   PIMPF - Produção física industrial por grupos e classes industriais selecionados  106 non-null    object
 1   A                                                                                 105 non-null    object
 2   B                                                                                 104 non-null    object
 3   C                                                                                 104 non-null    object
 4   D                                                                                 104 non-null    object
 5   E                                                                                 104 non-null    object
 6   F          

**Vamos eliminar algumas colunas desnecessarias**

In [0]:
df = df.drop(1)
df = df.drop(2)


**Redefinindo o index da base de dados**

In [0]:
df.set_index('PIMPF - Produção física industrial por grupos e classes industriais selecionados', inplace=True)

In [18]:
df.head(12)

A      B  ...     F     G
PIMPF - Produção física industrial por grupos e...                ...            
Brasil - abril 2020                                   NaN    NaN  ...   NaN   NaN
10.1 Abate e fabricação de produtos de carne         95.7   96.1  ...  -0.8   3.2
10.11 Abate de reses, exceto suínos                  91.5     90  ...  -6.6  -1.5
10.12 Abate de suínos, aves e outros pequenos a...   97.9  102.4  ...   5.4   8.1
10.13 Fabricação de produtos de carne               106.2   83.2  ...   -15    -4
10.3 Fabricação de conservas de frutas, legumes...   23.6   94.5  ...  -2.4  38.2
10.4 Fabricação de óleos e gorduras vegetais e ...  115.6   99.7  ...   2.1   0.6
10.41 Fabricação de óleos vegetais em bruto, ex...  126.2  100.5  ...   2.4   0.8
10.42 Fabricação de óleos vegetais refinados, e...  104.2  101.2  ...  -1.1   0.1
10.43 Fabricação de margarina e outras gorduras...   78.8   93.5  ...     3  -0.4
10.5 Laticínios                                        76   89.3  ... -13.1  -6.7
10.6 Moagem, fabricação de produtos amiláceos e...    100  101.3  ...   3.2   2.9

[12 rows x 7 columns]

**Verificando se existem linhas com valores duplicados**

In [19]:
df.duplicated()

PIMPF - Produção física industrial por grupos e classes industriais selecionados
Brasil - abril 2020                                                                                False
10.1 Abate e fabricação de produtos de carne                                                       False
10.11 Abate de reses, exceto suínos                                                                False
10.12 Abate de suínos, aves e outros pequenos animais                                              False
10.13 Fabricação de produtos de carne                                                              False
                                                                                                   ...  
32.3 Fabricação de artefatos para pesca e esporte                                                  False
32.4 Fabricação de brinquedos e jogos recreativos                                                  False
32.5 Fabricação de instrumentos e materiais para uso médico e odontológico e de

In [0]:
df.drop_duplicates(inplace= True)

In [21]:
df.duplicated()

PIMPF - Produção física industrial por grupos e classes industriais selecionados
Brasil - abril 2020                                                                                False
10.1 Abate e fabricação de produtos de carne                                                       False
10.11 Abate de reses, exceto suínos                                                                False
10.12 Abate de suínos, aves e outros pequenos animais                                              False
10.13 Fabricação de produtos de carne                                                              False
                                                                                                   ...  
32.1 Fabricação de artigos de joalheria, bijuteria e semelhantes                                   False
32.3 Fabricação de artefatos para pesca e esporte                                                  False
32.4 Fabricação de brinquedos e jogos recreativos                              

**Verificando valores nullos**

In [22]:
df.isnull().sum()

A    1
B    1
C    1
D    1
E    1
F    1
G    1
dtype: int64

**Calculando a media de cada variavel do dataframe**

In [23]:
df.mean()

A    61.301942
B    70.518447
C    91.794175
D    98.068932
E   -29.481553
F    -8.205825
G    -1.931068
dtype: float64

**preenchendo os valores nulos**

In [0]:
df = df.fillna(df.mean())

In [25]:
df

A  ...          G
PIMPF - Produção física industrial por grupos e...              ...           
Brasil - abril 2020                                  61.301942  ...  -1.931068
10.1 Abate e fabricação de produtos de carne         95.700000  ...   3.200000
10.11 Abate de reses, exceto suínos                  91.500000  ...  -1.500000
10.12 Abate de suínos, aves e outros pequenos a...   97.900000  ...   8.100000
10.13 Fabricação de produtos de carne               106.200000  ...  -4.000000
...                                                        ...  ...        ...
32.1 Fabricação de artigos de joalheria, bijute...   24.900000  ... -20.600000
32.3 Fabricação de artefatos para pesca e esporte    23.800000  ...  15.300000
32.4 Fabricação de brinquedos e jogos recreativos    18.400000  ...  -0.900000
32.5 Fabricação de instrumentos e materiais par...   54.000000  ...  -3.100000
32.9 Fabricação de produtos diversos                 70.300000  ...  -0.300000

[104 rows x 7 columns]

# Separando as variaveis preditivas e a variavel alvo

Nosso objetivo é prever os dados da coluna'G'

In [0]:
x = df.drop(['G'], axis=1)
y = df['G']


# Selection Features

**Testes estatisticos**


*   Usado para problema de classificaçao.
*   f_classif é adequado quando os dados sao numericos e a variavel alvo é categorica.


*   o mutual_info_classif é mais adequada quando quando nao há dependencia linear entre as features e a variável alvo.
*   f_regression aplicado para problemas de regressao.





In [27]:
!pip install scikit-learn

In [34]:
!pip install feature-selector 

In [0]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif, mutual_info_classif

**utilisando o test unitario**

In [30]:
f_classif = SelectKBest (score_func = f_classif,k=4)
fit = f_classif.fit(x,y)
features = fit.transform(x) 
print(features)

[[ 7.05184466e+01  9.17941748e+01 -2.94815534e+01 -8.20582524e+00]
 [ 9.61000000e+01  9.92000000e+01 -3.90000000e+00 -8.00000000e-01]
 [ 9.00000000e+01  9.34000000e+01 -1.00000000e+01 -6.60000000e+00]
 [ 1.02400000e+02  1.05400000e+02  2.40000000e+00  5.40000000e+00]
 [ 8.32000000e+01  8.50000000e+01 -1.68000000e+01 -1.50000000e+01]
 [ 9.45000000e+01  9.76000000e+01 -5.50000000e+00 -2.40000000e+00]
 [ 9.97000000e+01  1.02100000e+02 -3.00000000e-01  2.10000000e+00]
 [ 1.00500000e+02  1.02400000e+02  5.00000000e-01  2.40000000e+00]
 [ 1.01200000e+02  9.89000000e+01  1.20000000e+00 -1.10000000e+00]
 [ 9.35000000e+01  1.03000000e+02 -6.50000000e+00  3.00000000e+00]
 [ 8.93000000e+01  8.69000000e+01 -1.07000000e+01 -1.31000000e+01]
 [ 1.01300000e+02  1.03200000e+02  1.30000000e+00  3.20000000e+00]
 [ 1.10500000e+02  1.05800000e+02  1.05000000e+01  5.80000000e+00]
 [ 9.38000000e+01  1.01100000e+02 -6.20000000e+00  1.10000000e+00]
 [ 1.79200000e+02  1.54500000e+02  7.92000000e+01  5.45000000e

In [31]:
cols = fit.get_support(indices=True)
df.iloc[:,cols]

B  ...          F
PIMPF - Produção física industrial por grupos e...              ...           
Brasil - abril 2020                                  70.518447  ...  -8.205825
10.1 Abate e fabricação de produtos de carne         96.100000  ...  -0.800000
10.11 Abate de reses, exceto suínos                  90.000000  ...  -6.600000
10.12 Abate de suínos, aves e outros pequenos a...  102.400000  ...   5.400000
10.13 Fabricação de produtos de carne                83.200000  ... -15.000000
...                                                        ...  ...        ...
32.1 Fabricação de artigos de joalheria, bijute...   21.400000  ... -51.000000
32.3 Fabricação de artefatos para pesca e esporte    76.800000  ... -12.700000
32.4 Fabricação de brinquedos e jogos recreativos    32.300000  ...  -8.000000
32.5 Fabricação de instrumentos e materiais par...   47.500000  ... -17.400000
32.9 Fabricação de produtos diversos                 74.200000  ...  -4.400000

[104 rows x 4 columns]

**Utilisando o chi2 (USADO NORMALMENTE QUANDO TEMOS FEATURES CATEGORICOS E VARIAVEL ALVO CATEGORICA)**

In [0]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [33]:
# features extraction 
test = SelectKBest (chi2 ,k=4)
fit = test.fit(x,y)
fit.get_support(indices=True)


ValueError: ignored

**obs**

The error message Input X must be non-negative says it all: Pearson's chi square test (goodness of fit) does not apply to negative values. It's logical because the chi square test assumes frequencies distribution and a frequency can't be a negative number. Consequently, sklearn.feature_selection.chi2 asserts the input is non-negative.

You are saying that your features are "min, max, mean, median and FFT of accelerometer signal". In many cases, it may be quite safe to simply shift each feature to make it all positive, or even normalize to [0, 1] interval as suggested by EdChum.

If data transformation is for some reason not possible (e.g. a negative value is an important factor), you should pick another statistic to score your features:

sklearn.feature_selection.f_classif computes ANOVA f-value
sklearn.feature_selection.mutual_info_classif computes the mutual information
Since the whole point of this procedure is to prepare the features for another method, it's not a big deal to pick anyone, the end result usually the same or very close.

**Applicando o Recursive features Elimination - RFE**

**Code RFE**



```
from sklearn.linear_model import LogisticRegression
```





```
model = LogisticRegression(max_iter = 1000)
```





```
from sklearn.feature_selection import RFE
```





```
rfe = RFE(model,4)
```





```
fit = rfe.fit(x, y)
```





```
print("numero de features : {}".format(fit.n_features_)) 
```





```
cols = fit.get_support(indices=True)
df.iloc[:,cols]
```



**feature importance**



```
from sklearn.ensemble import RandomForestClassifier 
```





```
#Feature extration
model = RandomForestClassifier(n_estimators = 10)
model.fit(x,y)
```





```
print(model.feature_importances_)
```





```
colnames
```





```
# visualisando as features no dataframe
import pandas as pd
feature_importances = pd.DataFrame(mode1.feature_importances,
                      index = x.columns,
                      columns = ['feature_columns']).sort_values('feature_columns', ascending = False)    

```





```
feature_importances
```





```
# podemos plotar as feature_importances num grafico para visualizar lo
feature_importances.plot(kind='bar')

```



**Feature selection as part of a pipeline**



```
clf = Pipeline([
  ('feature_selection', RFE(LogisticRegression(max_iter = 2000),4)),
  ('classification', RandomForestClassifier())
])

```





```
clf.fit(X, y)
```





```
clf.steps
```



**Fim**